// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR2.Data;

#nullable disable

namespace PR2.Migrations
{
    [DbContext(typeof(MyApplicationContex))]
    [Migration("20231220145658_TableInputDatas")]
    partial class TableInputDatas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("PR2.Data.InputData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("TEXT");

                    b.Property<double>("O")
                        .HasColumnType("REAL");

                    b.Property<double>("TBOL")
                        .HasColumnType("REAL");

                    b.Property<double>("RASN_T_t")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("exp")
                        .HasColumnType("REAL");

                    b.Property<double>("mexp")
                        .HasColumnType("REAL");

                    b.Property<double>("tmal")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("InputDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
